on: [push, pull_request]
name: Test
jobs:
  lint:
    name: Check gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: gofmt
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: lint
          token: ${{ secrets.GITHUB_TOKEN }}
